### PR TITLE
Make changes to startup window and cleanup

### PR DESCRIPTION
**Pull request by asm512**
Moved all source files to `src` folder. Also resized the startup window because it was much too small, especially on 2k+ displays. I also added an event to the `Support/About` button since I assume you forgot this.

### CODE REVIEW

**Comment by Rbn3D** [comment]
Wow, first contribution! Thanks! 🎉 🎉 

Will checkout this, and if everything is Ok will merge
I guess the GithubBtn_Click() handler is not used anymore, could you delete it?

**Comment by Rbn3D** [comment]
Also, as you moved the project to src folder, could you please remove the original 'NativeDb_Explorer' folder? I assume you forgot (they are duplicated)

**Comment by asm512** [comment]
Sorry I didn't look for unused code, also I added a separate Github button, just forgot to push to the repo, all cleaned up now.

**Comment by Rbn3D** [comment]
Thank you!

**Pull request merged**
